export enum PcbOrderStatus {
  NEW = 'NEW',
  QUOTATION_SENT = 'QUOTATION_SENT',
  CONFIRMED = 'CONFIRMED',
  IN_PRODUCTION = 'IN_PRODUCTION',
  QUALITY_CHECK = 'QUALITY_CHECK',
  READY_FOR_SHIP = 'READY_FOR_SHIP',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ON_HOLD = 'ON_HOLD'
}

export enum PcbPaymentStatus {
  PENDING = 'PENDING',
  DEPOSIT_PAID = 'DEPOSIT_PAID',
  FULLY_PAID = 'FULLY_PAID',
  REFUNDED = 'REFUNDED',
  PAYMENT_FAILED = 'PAYMENT_FAILED'
}

export enum PcbOrderType {
  PCB = 'pcb',
  ASSEMBLY = 'assembly',
  STENCIL = 'stencil'
}